CREATE TABLE IF NOT EXISTS `chat`(
  `chat_id` INT UNSIGNED AUTO_INCREMENT,
  `chat_message` TEXT NOT NULL, 
  `chat_user` CHAR(50) NOT NULL, 
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY ( `chat_id` )
  )