CREATE TABLE IF NOT EXISTS `message` (
    `id` INT UNSIGNED AUTO_INCREMENT,
    `message` TEXT DEFAULT NULL,
    `room_id` INT NOT NULL,
    `user_id` INT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)